pragma Singleton
import QtQuick

// Loaded content of the preview (text/highlight/PDF/audio) --
// tenth singleton of the state/ layer. Different from state/PreviewState.qml
// (which only stores whether the panel is open/closed): this is the
// real result of loadPreview(), which stays in logic/PreviewLoader.qml.
QtObject {
  property var previewEntry: null
  property string previewText: ""
  property bool previewIsText: false
  // HTML with inline styles (Pygments, noclasses=True) for the fragment
  // being previewed -- empty if the language is not recognized or
  // highlight-preview.sh fails, in which case it falls back to the plain
  // Text of always with previewText. See PreviewLoader.loadPreview().
  property string previewHighlighted: ""
  // Render of the first page as PNG -- empty while it is generated or if it
  // fails, like videoThumbReady with videos. Phase 9: it is generated by
  // ThumbnailProvider (QPdfDocument) at preview size, no longer pdftoppm.
  property string previewPdfImage: ""
  // Image scaled to preview size (Phase 9): path of the
  // ThumbnailProvider thumbnail, "" while it is generated. Replaces loading the
  // full image file in the panel.
  property string previewImage: ""
  // Audio metadata (ffprobe): duration/format/bitrate/etc, same
  // { label, value } format that the Properties Repeater already uses.
  property var previewAudioInfo: []
  // Race guard, same mechanism as propertiesRequestId: loadPreview()
  // bumps this counter each time a new item is previewed and records
  // that number as the "owner" of each process it launches (text/highlight/
  // PDF/audio). Without this, quickly selecting a file A (with a slow highlight-
  // preview.sh/pdftoppm/ffprobe) and moving to a file B before it
  // finished let A's result, arriving late, be painted
  // over B's preview.
  property int previewRequestId: 0
  property int _previewTextOwner: -1
  property int _previewHighlightOwner: -1
  property int _previewPdfOwner: -1
  property int _previewImageOwner: -1
  property int _previewAudioOwner: -1
}
